const songsArr = [
	{
		id: "rep-01",
		data_name: "ready_for_it",
		title: "...Ready for it?",
		lyrics: [
			"Knew he was a killer first time that I saw him<BREAKER>Wonder how many girls he had loved and left haunted<BREAKER>But if he's a ghost, then I can be a phantom<BREAKER>Holdin' him for ransom",
			"Some, some boys are tryin' too hard<BREAKER>He don't try at all, though<BREAKER>Younger than my exes but he act like such a man, so<BREAKER>I see nothing better, I keep him forever<BREAKER>Like a vendetta-ta",
			"I-I-I see how this is gon' go<BREAKER>Touch me and you'll never be alone<BREAKER>I-Island breeze and lights down low<BREAKER>No one has to know",
			"In the middle of the night, in my dreams (my dreams)<BREAKER>You should see the things we do (we do), baby (baby, mmm, eh)<BREAKER>In the middle of the night, in my dreams (my dreams)<BREAKER>I know I'm gonna be with you<BREAKER>So I take my time (eh)<BREAKER>In the middle of the night",
			"Baby, let the games begin<BREAKER>Let the games begin<BREAKER>Let the games begin<BREAKER>Are you ready for it?<BREAKER>Baby, let the games begin<BREAKER>Let the games begin<BREAKER>Let the games begin<BREAKER>Are you ready for it?",
		],
	},
	{
		id: "rep-02",
		data_name: "end_game",
		title: "End Game",
		lyrics: [
			"I wanna be your endgame<BREAKER>I wanna be your first string<BREAKER>I wanna be your A-Team (whoa-whoa, whoa)<BREAKER>I wanna be your endgame, endgame",
			"Big reputation, big reputation<BREAKER>Ooh, you and me, we got big reputations, ah<BREAKER>And you heard about me, ooh<BREAKER>I got some big enemies (yeah)<BREAKER>Big reputation, big reputation<BREAKER>Ooh, you and me, we'd be a big conversation, ah<BREAKER>And I heard about you, ooh (yeah)<BREAKER>You like the bad ones too",
			"You so dope, don't overdose<BREAKER>I'm so stoked, I need a toast<BREAKER>We do the most<BREAKER>I'm in the Ghost like I'm whippin' a boat<BREAKER>I got a reputation, girl, that don't precede me (yeah)<BREAKER>I'm one call away, whenever you need me (yeah)<BREAKER>I'm on a G5 (yeah), come to the A-Side (yeah)<BREAKER>I got a bad boy persona, that's what they like<BREAKER>You love it, I love it too 'cause you my type<BREAKER>You hold me down and I protect you with my life",
			"I don't wanna touch you (I don't wanna be)<BREAKER>Just another ex-love (you don't wanna see)<BREAKER>I don't wanna miss you (I don't wanna miss you)<BREAKER>Like the other girls do<BREAKER>I don't wanna hurt you (I just wanna be)<BREAKER>Drinkin' on a beach with (you all over me)<BREAKER>I know what they all say (I know what they all say)<BREAKER>But I ain't tryna play",
			"I wanna be your endgame (endgame)<BREAKER>I wanna be your first string (first string)<BREAKER>I wanna be your A-Team (A-Team)<BREAKER>I wanna be your endgame, endgame",
			"Knew her when I was young<BREAKER>Reconnected when we were little bit older<BREAKER>Both sprung, I got issues and chips on both of my shoulders<BREAKER>Reputation precedes me, in rumors I'm knee-deep<BREAKER>The truth is, it's easier to ignore it, believe me<BREAKER>Even when we'd argue, we'd not do it for long<BREAKER>And you understand the good and bad end up in the song<BREAKER>For all your beautiful traits, and the way you do it with ease<BREAKER>For all my flaws, paranoia, and insecurities<BREAKER>I've made mistakes, and made some choices that's hard to deny<BREAKER>After the storm, something was born on the Fourth of July<BREAKER>I've passed days without fun, this endgame is the one<BREAKER>With four words on the tip of my tongue I'll never say",
			"I don't wanna touch you (I don't wanna be)<BREAKER>Just another ex-love (you don't wanna see)<BREAKER>I don't wanna miss you (I don't wanna miss you)<BREAKER>Like the other girls do<BREAKER>I don't wanna hurt you (I just wanna be)<BREAKER>Drinkin' on a beach with (you all over me)<BREAKER>I know what they all say, yeah<BREAKER>But I ain't tryna play",
			"I wanna be your endgame (endgame)<BREAKER>I wanna be your first string (wanna be your first string)<BREAKER>I wanna be your A-Team (A-Team)<BREAKER>I wanna be your endgame, endgame",
			"Big reputation, big reputation<BREAKER>Ooh, you and me, we got big reputations, ah<BREAKER>And you heard about me, oh<BREAKER>I got some big enemies (hey)<BREAKER>Big reputation, big reputation (yeah)<BREAKER>Ooh, you and me, we'd be a big conversation, ah<BREAKER>And I heard about you, ooh<BREAKER>You like the bad ones too",
			"I hit you like, \"Bang\"<BREAKER>We tried to forget it, but we just couldn't<BREAKER>And I bury hatchets but I keep maps of where I put 'em<BREAKER>Reputation precedes me, they told you I'm crazy<BREAKER>I swear I don't love the drama, it loves me<BREAKER>And I can't let you go, your handprint's on my soul<BREAKER>It's like your eyes are liquor, it's like your body is gold<BREAKER>You've been calling my bluff on all my usual tricks<BREAKER>So here's the truth from my red lips",
			"I wanna be your endgame (endgame)<BREAKER>I wanna be your first string (me and you) (first string)<BREAKER>I wanna be your A-Team (be your A-Team now)<BREAKER>I wanna be your endgame, endgame<BREAKER>I wanna be your endgame (oh, I do)<BREAKER>I wanna be your first string (first string)<BREAKER>I wanna be your A-Team (A-Team)<BREAKER>I wanna be your endgame, endgame",
		],
	},
	{
		id: "rep-03",
		data_name: "i_did_something_bad",
		title: "I Did Something Bad",
		lyrics: [
			"I never trust a narcissist<BREAKER>But they love me<BREAKER>So I play 'em like a violin<BREAKER>And I make it look oh so easy<BREAKER>'Cause for every lie I tell them<BREAKER>They tell me three<BREAKER>This is how the world works<BREAKER>Now all he thinks about is me",
			"I can feel the flames on my skin<BREAKER>Crimson red paint on my lips<BREAKER>If a man talks shit, then I owe him nothing<BREAKER>I don't regret it one bit, 'cause he had it coming",
			"They say I did something bad<BREAKER>Then why's it feel so good?<BREAKER>They say I did something bad<BREAKER>But why's it feel so good?<BREAKER>Most fun I ever had<BREAKER>And I'd do it over and over and over again if I could<BREAKER>It just felt so good, good",
			"I never trust a playboy<BREAKER>But they love me<BREAKER>So I fly him all around the world<BREAKER>And I let them think they saved me<BREAKER>They never see it comin'<BREAKER>What I do next<BREAKER>This is how the world works<BREAKER>You gotta leave before you get left",
			"I can feel the flames on my skin<BREAKER>He says, \"Don't throw away a good thing\"<BREAKER>But if he drops my name, then I owe him nothin'<BREAKER>And if he spends my change, then he had it comin'",
			"They say I did something bad<BREAKER>Then why's it feel so good?<BREAKER>They say I did something bad<BREAKER>But why's it feel so good?<BREAKER>Most fun I ever had<BREAKER>And I'd do it over and over and over again if I could<BREAKER>It just felt so good, good",
			"It just felt so good",
			"They're burning all the witches, even if you aren't one<BREAKER>They got their pitchforks and proof<BREAKER>Their receipts and reasons<BREAKER>They're burning all the witches, even if you aren't one<BREAKER>So light me up (light me up), light me up (light me up)<BREAKER>Light me up, go ahead and light me up (light me up)<BREAKER>Light me up (light me up), light me up (light me up)<BREAKER>Light me up (light me up), light me up (light me up)",
			"They say I did something bad<BREAKER>Then why's it feel so good?<BREAKER>They say I did something bad<BREAKER>But why's it feel so good?<BREAKER>Most fun I ever had<BREAKER>And I'd do it over and over and over again if I could<BREAKER>It just felt so good, good",
			"Oh, you say I did something bad<BREAKER>Then why's it feel so good, good?<BREAKER>So bad, why's it feel so good?<BREAKER>Why's it feel, why's it feel so good? (Bad)<BREAKER>It just felt so good, good",
		],
	},
	{
		id: "rep-04",
		data_name: "dont_blame_me",
		title: "Don't Blame Me",
		lyrics: [
			"Don't blame me, love made me crazy<BREAKER>If it doesn't, you ain't doin' it right<BREAKER>Lord, save me, my drug is my baby<BREAKER>I'll be usin' for the rest of my life",
			"I've been breakin' hearts a long time, and<BREAKER>Toyin' with them older guys<BREAKER>Just playthings for me to use<BREAKER>Something happened for the first time, in<BREAKER>The darkest little paradise<BREAKER>Shakin', pacin', I just need you",
			'For you, I would cross the line<BREAKER>I would waste my time<BREAKER>I would lose my mind<BREAKER>They say, "She\'s gone too far this time"',
			"Don't blame me, love made me crazy<BREAKER>If it doesn't, you ain't doin' it right<BREAKER>Lord, save me, my drug is my baby<BREAKER>I'll be usin' for the rest of my life<BREAKER>Don't blame me, love made me crazy<BREAKER>If it doesn't, you ain't doin' it right<BREAKER>Oh, Lord, save me, my drug is my baby<BREAKER>I'll be usin' for the rest of my life",
			"My name is whatever you decide<BREAKER>And I'm just gonna call you mine<BREAKER>I'm insane, but I'm your baby (your baby)<BREAKER>Echoes (echoes) of your name inside my mind<BREAKER>Halo, hiding my obsession<BREAKER>I once was poison ivy, but now I'm your daisy",
			"And baby, for you, I (I) would (would) fall from grace<BREAKER>Just (just) to (to) touch your face<BREAKER>If (if) you (you) walk away<BREAKER>I'd beg you on my knees to stay",
			"Don't blame me, love made me crazy<BREAKER>If it doesn't, you ain't doin' it right<BREAKER>Lord, save me, my drug is my baby<BREAKER>I'll be usin' for the rest of my life (yeah, ooh)<BREAKER>Don't blame me, love made me crazy<BREAKER>If it doesn't, you ain't doin' it right<BREAKER>Oh, Lord, save me, my drug is my baby<BREAKER>I'll be usin' for the rest of my life",
			"I get so high, oh<BREAKER>Every time you're, every time you're lovin' me<BREAKER>You're lovin' me<BREAKER>Trip of my life, oh<BREAKER>Every time you're, every time you're touchin' me<BREAKER>You're touchin' me",
			"Every time you're, every time you're lovin' me<BREAKER>Oh Lord, save me, my drug is my baby<BREAKER>I'll be usin' for the rest of my life<BREAKER>Usin' for the rest of my life, ohh-oh",
			"Don't blame me, love made me crazy<BREAKER>If it doesn't, you ain't doin' it right (doin' it right, no)<BREAKER>Lord, save me, my drug is my baby<BREAKER>I'll be usin' for the rest of my life (oh)<BREAKER>Don't blame me, love made me crazy (ooh)<BREAKER>If it doesn't, you ain't doin' it right (you ain't doin' it right)<BREAKER>Oh, Lord, save me, my drug is my baby<BREAKER>I'll be usin' for (I'll be usin') the rest of my life (I'll be usin')",
			"I get so high, oh<BREAKER>Every time you're, every time you're lovin' me<BREAKER>You're lovin' me<BREAKER>Oh, Lord, save me, my drug is my baby<BREAKER>I'll be usin' for the rest of my life",
		],
	},
	{
		id: "rep-05",
		data_name: "delicate",
		title: "Delicate",
		lyrics: [
			"This ain't for the best<BREAKER>My reputation's never been worse, so<BREAKER>You must like me for me<BREAKER>We can't make<BREAKER>Any promises now, can we, babe?<BREAKER>But you can make me a drink",
			"Dive bar on the East Side, where you at?<BREAKER>Phone lights up my nightstand in the black<BREAKER>Come here, you can meet me in the back<BREAKER>Dark jeans and your Nikes, look at you<BREAKER>Oh damn, never seen that color blue<BREAKER>Just think of the fun things we could do",
			"This ain't for the best<BREAKER>My reputation's never been worse, so<BREAKER>You must like me for me<BREAKER>(Yeah, I want you)<BREAKER>We can't make<BREAKER>Any promises now, can we, babe?<BREAKER>But you can make me a drink",
			"Is it cool that I said all that?<BREAKER>Is it chill that you're in my head?<BREAKER>'Cause I know that it's delicate (delicate)<BREAKER>Is it cool that I said all that?<BREAKER>Is it too soon to do this yet?<BREAKER>'Cause I know that it's delicate",
			"Isn't it, isn't it, isn't it?<BREAKER>Isn't it?<BREAKER>Isn't it, isn't it, isn't it?<BREAKER>Isn't it delicate?",
			"Third floor on the West Side, me and you<BREAKER>Handsome, you're a mansion with a view<BREAKER>Do the girls back home touch you like I do?<BREAKER>Long night with your hands up in my hair<BREAKER>Echoes of your footsteps on the stairs<BREAKER>Stay here, honey, I don't wanna share",
			"This ain't for the best<BREAKER>My reputation's never been worse, so<BREAKER>You must like me for me<BREAKER>(Yeah, I want you)<BREAKER>We can't make<BREAKER>Any promises now, can we, babe?<BREAKER>But you can make me a drink",
			"Is it cool that I said all that?<BREAKER>Is it chill that you're in my head?<BREAKER>'Cause I know that it's delicate (delicate)<BREAKER>Is it cool that I said all that?<BREAKER>Is it too soon to do this yet?<BREAKER>'Cause I know that it's delicate",
			"Isn't it, isn't it, isn't it?<BREAKER>Isn't it?<BREAKER>Isn't it, isn't it, isn't it?<BREAKER>Isn't it delicate?",
			"Sometimes I wonder, when you sleep<BREAKER>Are you ever dreaming of me?<BREAKER>Sometimes when I look into your eyes<BREAKER>I pretend you're mine all the damn time",
			"Is it cool that I said all that?<BREAKER>Is it chill that you're in my head?<BREAKER>'Cause I know that it's delicate (delicate)<BREAKER>(Yeah, I want you)<BREAKER>Is it cool that I said all that?<BREAKER>Is it too soon to do this yet?<BREAKER>'Cause I know that it's delicate (delicate)",
			"Is it cool that I said all that? (Isn't it?)<BREAKER>Is it chill that you're in my head? (Isn't it, isn't it?)<BREAKER>'Cause I know that it's delicate (isn't it delicate?)<BREAKER>(Yeah, I want you)<BREAKER>Is it cool that I said all that? (Isn't it?)<BREAKER>Is it too soon to do this yet? (Isn't it, isn't it?)<BREAKER>'Cause I know that it's delicate",
			"Isn't it delicate?",
		],
	},
	{
		id: "rep-06",
		data_name: "look_what_you_made_me_do",
		title: "Look What You Made Me Do",
		lyrics: [
			"I don't like your little games<BREAKER>Don't like your tilted stage<BREAKER>The role you made me play of the fool<BREAKER>No, I don't like you",
			"I don't like your perfect crime<BREAKER>How you laugh when you lie<BREAKER>You said the gun was mine<BREAKER>Isn't cool, no, I don't like you (oh!)",
			"But I got smarter, I got harder in the nick of time<BREAKER>Honey, I rose up from the dead, I do it all the time<BREAKER>I got a list of names, and yours is in red, underlined<BREAKER>I check it once, then I check it twice, oh!",
			"Ooh, look what you made me do<BREAKER>Look what you made me do<BREAKER>Look what you just made me do<BREAKER>Look what you just made me...<BREAKER>Ooh, look what you made me do<BREAKER>Look what you made me do<BREAKER>Look what you just made me do<BREAKER>Look what you just made me do",
			"I (I) don't (don't) like your kingdom keys (keys)<BREAKER>They (they) once belonged to me (me)<BREAKER>You (you) asked me for a place to sleep<BREAKER>Locked me out and threw a feast (what?)",
			"The world moves on, another day another drama, drama<BREAKER>But not for me, not for me, all I think about is karma<BREAKER>And then the world moves on, but one thing's for sure<BREAKER>Maybe I got mine, but you'll all get yours",
			"But I got smarter, I got harder in the nick of time (nick of time)<BREAKER>Honey, I rose up from the dead, I do it all the time (I do it all the time)<BREAKER>I got a list of names, and yours is in red, underlined<BREAKER>I check it once, then I check it twice, oh!",
			"Ooh, look what you made me do<BREAKER>Look what you made me do<BREAKER>Look what you just made me do<BREAKER>Look what you just made me...<BREAKER>Ooh, look what you made me do<BREAKER>Look what you made me do<BREAKER>Look what you just made me do<BREAKER>Look what you just made me do",
			"I don't trust nobody and nobody trusts me<BREAKER>I'll be the actress starring in your bad dreams<BREAKER>I don't trust nobody and nobody trusts me<BREAKER>I'll be the actress starring in your bad dreams<BREAKER>I don't trust nobody and nobody trusts me<BREAKER>I'll be the actress starring in your bad dreams<BREAKER>I don't trust nobody and nobody trusts me<BREAKER>I'll be the actress starring in your bad dreams",
			"I'm sorry<BREAKER>But the old Taylor can't come to the phone right now<BREAKER>Why? Oh, 'cause she's dead (oh)",
			"Ooh, look what you made me do<BREAKER>Look what you made me do<BREAKER>Look what you just made me do<BREAKER>Look what you just made me...<BREAKER>Ooh, look what you made me do<BREAKER>Look what you made me do<BREAKER>Look what you just made me do<BREAKER>Look what you just made me do",
			"Ooh, look what you made me do<BREAKER>Look what you made me do<BREAKER>Look what you just made me do<BREAKER>Look what you just made me...<BREAKER>Ooh, look what you made me do<BREAKER>Look what you made me do<BREAKER>Look what you just made me do<BREAKER>Look what you just made me do",
		],
	},
	{
		id: "rep-07",
		data_name: "so_it_goes",
		title: "So It Goes...",
		lyrics: [
			"See you in the dark<BREAKER>All eyes on you, my magician<BREAKER>All eyes on us<BREAKER>You make everyone disappear, and<BREAKER>Cut me into pieces<BREAKER>Gold cage, hostage to my feelings<BREAKER>Back against the wall<BREAKER>Trippin', trip-trippin' when you're gone",
			"'Cause we breakdown a little<BREAKER>But when you get me alone, it's so simple<BREAKER>'Cause baby, I know what you know<BREAKER>We can feel it",
			"And all the pieces fall<BREAKER>Right into place<BREAKER>Getting caught up in a moment<BREAKER>Lipstick on your face<BREAKER>So it goes<BREAKER>I'm yours to keep<BREAKER>And I'm yours to lose<BREAKER>You know I'm not a bad girl<BREAKER>But I do bad things with you<BREAKER>So it goes",
			"Met you in a bar<BREAKER>All eyes on me, your illusionist<BREAKER>All eyes on us<BREAKER>I make all your gray days clear and<BREAKER>Wear you like a necklace<BREAKER>I'm so chill, but you make me jealous<BREAKER>But I got your heart<BREAKER>Skippin', skip-skippin' when I'm gone",
			"'Cause we breakdown a little<BREAKER>But when I get you alone, it's so simple<BREAKER>'Cause baby, I know what you know<BREAKER>We can feel it",
			"And all the pieces fall<BREAKER>Right into place<BREAKER>Getting caught up in a moment<BREAKER>Lipstick on your face<BREAKER>So it goes<BREAKER>I'm yours to keep<BREAKER>And I'm yours to lose<BREAKER>You know I'm not a bad girl<BREAKER>But I do bad things with you<BREAKER>So it goes",
			"Come here, dressed in black now<BREAKER>So, so, so it goes<BREAKER>Scratches down your back now<BREAKER>So, so, so it goes",
			"You did a number on me<BREAKER>But honestly, baby, who's counting?<BREAKER>I did a number on you<BREAKER>But honestly, baby, who's counting?<BREAKER>You did a number on me<BREAKER>But honestly, baby, who's counting?<BREAKER>Who's counting?<BREAKER>(One, two, three)",
			"And all the pieces fall<BREAKER>Right into place<BREAKER>Getting caught up in a moment<BREAKER>Lipstick on your face<BREAKER>So it goes<BREAKER>I'm yours to keep<BREAKER>And I'm yours to lose<BREAKER>You know I'm not a bad girl<BREAKER>But I do bad things with you<BREAKER>So it goes",
			"Come here, dressed in black now<BREAKER>So, so, so it goes<BREAKER>Scratches down your back now<BREAKER>So, so, so it goes<BREAKER>Come here, dressed in black now<BREAKER>So, so, so it goes<BREAKER>Scratches down your back now<BREAKER>So, so, so it goes",
		],
	},
	{
		id: "rep-08",
		data_name: "gorgeous",
		title: "Gorgeous",
		lyrics: [
			"You should take it as a compliment<BREAKER>That I got drunk and made fun of the way you talk<BREAKER>You should think about the consequence<BREAKER>Of your magnetic field being a little too strong<BREAKER>And I got a boyfriend, he's older than us<BREAKER>He's in the club doing, I don't know what<BREAKER>You're so cool, it makes me hate you so much (I hate you so much)",
			"Whisky on ice, Sunset and Vine<BREAKER>You've ruined my life, by not being mine",
			"You're so gorgeous<BREAKER>I can't say anything to your face<BREAKER>'Cause look at your face (gorgeous)<BREAKER>And I'm so furious<BREAKER>At you for making me feel this way<BREAKER>But what can I say?<BREAKER>You're gorgeous",
			"You should take it as a compliment<BREAKER>That I'm talking to everyone here but you (but you, but you)<BREAKER>And you should think about the consequence<BREAKER>Of you touching my hand in the darkened room (dark room, dark room)<BREAKER>If you've got a girlfriend, I'm jealous of her<BREAKER>But if you're single that's honestly worse<BREAKER>'Cause you're so gorgeous it actually hurts<BREAKER>(Honey, it hurts)",
			"Ocean blue eyes looking in mine<BREAKER>I feel like I might sink and drown and die",
			"You're so gorgeous<BREAKER>I can't say anything to your face (to your face)<BREAKER>'Cause look at your face (look at your face)<BREAKER>And I'm so furious<BREAKER>At you for making me feel this way (this way)<BREAKER>But what can I say?<BREAKER>You're gorgeous",
			"You make me so happy, it turns back to sad, yeah<BREAKER>There's nothing I hate more than what I can't have<BREAKER>You are so gorgeous it makes me so mad (mmh)<BREAKER>You make me so happy, it turns back to sad, yeah<BREAKER>There's nothing I hate more than what I can't have and<BREAKER>Guess I'll just stumble on home to my cats (yeugh)<BREAKER>Alone, unless you wanna come along (oh)",
			"You're so gorgeous<BREAKER>I can't say anything to your face (to your face)<BREAKER>'Cause look at your face (look at your face, gorgeous)<BREAKER>And I'm so furious (I'm so furious)<BREAKER>At you for making me feel this way (feel this way)<BREAKER>But what can I say? (I say)<BREAKER>You're gorgeous",
			"You make me so happy, it turns back to sad, yeah<BREAKER>There's nothing I hate more than what I can't have and<BREAKER>You are so gorgeous it makes me so mad (mmh)<BREAKER>You're gorgeous<BREAKER>You make me so happy, it turns back to sad, yeah (it turns back so sad)<BREAKER>There's nothing I hate more than what I can't have (what I can have)<BREAKER>You are so gorgeous it makes me so mad (mmh)<BREAKER>You're gorgeous",
		],
	},
	{
		id: "rep-09",
		data_name: "getaway_car",
		title: "Getaway Car",
		lyrics: [
			"No, nothin' good starts in a getaway car",
			"It was the best of times, the worst of crimes<BREAKER>I struck a match and blew your mind<BREAKER>But I didn't mean it, and you didn't see it<BREAKER>The ties were black, the lies were white<BREAKER>In shades of gray in candlelight<BREAKER>I wanted to leave him, I needed a reason",
			'"X" marks the spot where we fell apart<BREAKER>He poisoned the well, I was lyin\' to myself<BREAKER>I knew it from the first Old Fashioned, we were cursed<BREAKER>We never had a shotgun shot in the dark (oh!)',
			"You were drivin' the getaway car<BREAKER>We were flyin', but we'd never get far<BREAKER>Don't pretend it's such a mystery<BREAKER>Think about the place where you first met me<BREAKER>Ridin' in a getaway car<BREAKER>There were sirens in the beat of your heart<BREAKER>Should've known I'd be the first to leave<BREAKER>Think about the place where you first met me<BREAKER>In a getaway car, oh-oh-oh<BREAKER>No, they never get far, oh-oh-ah<BREAKER>No, nothin' good starts in a getaway car",
			"It was the great escape, the prison break<BREAKER>The light of freedom on my face<BREAKER>But you weren't thinkin' and I was just drinkin'<BREAKER>While he was runnin' after us, I was screamin', \"Go, go, go!\"<BREAKER>But with three of us, honey, it's a sideshow<BREAKER>And a circus ain't a love story, and now we're both sorry (we're both sorry)",
			'"X" marks the spot where we fell apart<BREAKER>He poisoned the well, every man for himself<BREAKER>I knew it from the first Old Fashioned, we were cursed<BREAKER>It hit you like a shotgun shot to the heart (oh!)',
			"You were drivin' the getaway car<BREAKER>We were flyin', but we'd never get far<BREAKER>Don't pretend it's such a mystery<BREAKER>Think about the place where you first met me<BREAKER>Ridin' in a getaway car<BREAKER>There were sirens in the beat of your heart<BREAKER>Should've known I'd be the first to leave<BREAKER>Think about the place where you first met me<BREAKER>In a getaway car, oh-oh-oh<BREAKER>No, they never get far, oh-oh-ah<BREAKER>No, nothin' good starts in a getaway car",
			"We were jet-set, Bonnie and Clyde (oh-oh)<BREAKER>Until I switched to the other side, to the other side<BREAKER>It's no surprise I turned you in (oh-oh)<BREAKER>'Cause us traitors never win",
			"I'm in a getaway car<BREAKER>I left you in a motel bar<BREAKER>Put the money in a bag and I stole the keys<BREAKER>That was the last time you ever saw me (oh!)",
			"Drivin' the getaway car<BREAKER>We were flyin', but we'd never get far (don't pretend)<BREAKER>Don't pretend it's such a mystery<BREAKER>Think about the place where you first met me<BREAKER>Ridin' in a getaway car<BREAKER>There were sirens in the beat of your heart (should've known)<BREAKER>Should've known I'd be the first to leave<BREAKER>Think about the place where you first met me<BREAKER>In a getaway car, oh-oh-oh<BREAKER>No, they never get far, oh-oh-ah<BREAKER>No, nothin' good starts in a getaway car",
			"I was ridin' in a getaway car<BREAKER>I was cryin' in a getaway car<BREAKER>I was dyin' in a getaway car<BREAKER>Said goodbye in a getaway car<BREAKER>Ridin' in a getaway car<BREAKER>I was cryin' in a getaway car<BREAKER>I was dyin' in a getaway car<BREAKER>Said goodbye in a getaway car",
		],
	},
	{
		id: "rep-10",
		data_name: "king_of_my_heart",
		title: "King Of My Heart",
		lyrics: [
			"I'm perfectly fine, I live on my own<BREAKER>I made up my mind, I'm better off bein' alone<BREAKER>We met a few weeks ago<BREAKER>Now you try on callin' me 'baby' like tryin' on clothes",
			"Salute to me, I'm your American queen<BREAKER>And you move to me like I'm a Motown beat<BREAKER>And we rule the kingdom inside my room<BREAKER>'Cause all the boys and their expensive cars<BREAKER>With their Range Rovers and their Jaguars<BREAKER>Never took me quite where you do",
			"And all at once, you are the one I have been waitin' for<BREAKER>King of my heart, body and soul, woah<BREAKER>And all at once, you're all I want, I'll never let you go<BREAKER>King of my heart, body and soul, woah",
			"And all at once<BREAKER>I've been waitin', waitin'<BREAKER>Woah, woah<BREAKER>And all at once<BREAKER>You are the one, I have been waitin', waitin'<BREAKER>Body and soul, woah<BREAKER>And all at once",
			"Late in the night, the city's asleep<BREAKER>Your love is a secret I'm hoping, dreaming, dying to keep<BREAKER>Change my priorities<BREAKER>The taste of your lips is my idea of luxury",
			"Salute to me, I'm your American queen<BREAKER>And you move to me like I'm a Motown beat<BREAKER>And we rule the kingdom inside my room (Inside my room, oh)<BREAKER>'Cause all the boys and their expensive cars<BREAKER>With their Range Rovers and their Jaguars<BREAKER>Never took me quite where you do (Where you do)",
			"And all at once, you are the one I have been waitin' for<BREAKER>King of my heart, body and soul, woah<BREAKER>And all at once, you're all I want, I'll never let you go<BREAKER>King of my heart (My heart), body and soul, woah",
			"And all at once (Hey)<BREAKER>I've been waitin', waitin' (Waiting)<BREAKER>Woah, woah<BREAKER>And all at once<BREAKER>You are the one I have been waitin' (Waitin'), waitin' (Waitin')<BREAKER>Body and soul, woah<BREAKER>And all at once",
			"Is this the end of all the endings?<BREAKER>My broken bones are mending<BREAKER>With all these nights we're spending<BREAKER>Up on the roof with a school girl crush<BREAKER>Drinkin' beer out of plastic cups<BREAKER>Say you fancy me, not fancy stuff<BREAKER>Baby, all at once, this is enough",
			"And all at once, you are the one I have been waitin' for<BREAKER>King of my heart, body and soul, woah (And all at once)",
			"And all at once, you are the one I have been waitin' for<BREAKER>King of my heart, body and soul, woah<BREAKER>And all at once, you're all I want, I'll never let you go<BREAKER>King of my heart (My heart), body and soul (My soul), woah",
			"And all at once<BREAKER>I've been waitin', waitin'<BREAKER>Woah, woah (Woah)<BREAKER>And all at once<BREAKER>You are the one I have been waitin', waitin'<BREAKER>Body and soul, woah<BREAKER>And all at once",
		],
	},
	{
		id: "rep-11",
		data_name: "dancing_with_our_hands_tied",
		title: "Dancing With Our Hands Tied",
		lyrics: [
			"I, I loved you in secret<BREAKER>First sight, yeah, we love without reason<BREAKER>Oh, twenty-five years old<BREAKER>Oh, how were you to know, and<BREAKER>My, my love had been frozen<BREAKER>Deep blue, but you painted me golden<BREAKER>Oh, and you held me close<BREAKER>Oh, how was I to know that",
			"I could've spent forever with your hands in my pockets<BREAKER>Picture of your face in an invisible locket<BREAKER>You said there was nothing in the world that could stop it<BREAKER>I had a bad feeling<BREAKER>And darling, you had turned my bed into a sacred oasis<BREAKER>People started talking, putting us through our paces<BREAKER>I knew there was no one in the world who could take it<BREAKER>I had a bad feeling",
			"But we were dancing<BREAKER>Dancing with our hands tied, hands tied<BREAKER>Yeah, we were dancing<BREAKER>Like it was the first time, first time<BREAKER>Yeah, we were dancing<BREAKER>Dancing with our hands tied, hands tied<BREAKER>Yeah, we were dancing<BREAKER>And I had a bad feeling<BREAKER>But we were dancing",
			"I, I loved you in spite of<BREAKER>Deep fears that the world would divide us<BREAKER>So, baby, can we dance<BREAKER>Oh, through an avalanche?<BREAKER>And say, say that we got it<BREAKER>I'm a mess, but I'm the mess that you wanted<BREAKER>Oh, 'cause it's gravity<BREAKER>Oh, keeping you with me",
			"I could've spent forever with your hands in my pockets<BREAKER>Picture of your face in an invisible locket<BREAKER>You said there was nothing in the world that could stop it<BREAKER>I had a bad feeling",
			"But we were dancing<BREAKER>Dancing with our hands tied, hands tied<BREAKER>Yeah, we were dancing<BREAKER>Like it was the first time, first time<BREAKER>Yeah, we were dancing<BREAKER>Dancing with our hands tied, hands tied<BREAKER>Yeah, we were dancing<BREAKER>(Ooh, we had our hands tied)<BREAKER>And I had a bad feeling<BREAKER>But we were dancing",
			"I'd kiss you as the lights went out<BREAKER>Swaying as the room burned down<BREAKER>I'd hold you as the water rushes in<BREAKER>If I could dance with you again<BREAKER>I'd kiss you as the lights went out<BREAKER>Swaying as the room burned down<BREAKER>I'd hold you as the water rushes in<BREAKER>If I could dance with you again",
			"Dancing with our hands tied, hands tied<BREAKER>Yeah, we were dancing<BREAKER>Like it was the first time, first time<BREAKER>Yeah, we were dancing<BREAKER>Dancing with our hands tied, hands tied<BREAKER>Yeah, we were dancing<BREAKER>And I had a bad feeling<BREAKER>But we were dancing<BREAKER>Hands tied, hands tied",
		],
	},
	{
		id: "rep-12",
		data_name: "dress",
		title: "Dress",
		lyrics: [
			"Our secret moments in your crowded room<BREAKER>They got no idea about me and you<BREAKER>There is an indentation in the shape of you<BREAKER>Made your mark on me, a golden tattoo",
			"All of this silence and patience, pining in anticipation<BREAKER>My hands are shaking from holding back from you (ah, ah, ah)<BREAKER>All of this silence and patience, pining and desperately waiting<BREAKER>My hands are shaking from all this (ah, ha, ha, ha)",
			"Say my name and everything just stops<BREAKER>I don't want you like a best friend<BREAKER>Only bought this dress so you could take it off<BREAKER>Take it off<BREAKER>Carve your name into my bedpost<BREAKER>'Cause I don't want you like a best friend<BREAKER>Only bought this dress so you could take it off<BREAKER>Take it off",
			"Inescapable, I'm not even gonna try<BREAKER>And if I get burned, at least we were electrified<BREAKER>I'm spilling wine in the bathtub<BREAKER>You kiss my face and we're both drunk<BREAKER>Everyone thinks that they know us<BREAKER>But they know nothing about",
			"All of this silence and patience, pining in anticipation<BREAKER>My hands are shaking from holding back from you (ah, ah, ah)<BREAKER>All of this silence and patience, pining and desperately waiting<BREAKER>My hands are shaking from all this (ah, ha, ha, ha)",
			"Say my name and everything just stops<BREAKER>I don't want you like a best friend<BREAKER>Only bought this dress so you could take it off<BREAKER>Take it off<BREAKER>Carve your name into my bedpost<BREAKER>'Cause I don't want you like a best friend<BREAKER>Only bought this dress so you could take it off<BREAKER>Take it off<BREAKER>Only bought this dress so you could take it off<BREAKER>Only bought this dress so you could take it off",
			"Flashback when you met me<BREAKER>Your buzzcut and my hair bleached<BREAKER>Even in my worst times<BREAKER>You could see the best of me<BREAKER>Flashback to my mistakes<BREAKER>My rebounds, my earthquakes<BREAKER>Even in my worst lies<BREAKER>You saw the truth in me<BREAKER>And I woke up just in time<BREAKER>Now I wake up by your side<BREAKER>My one and only, my lifeline<BREAKER>I woke up just in time<BREAKER>Now I wake up by your side<BREAKER>My hands shake, I can't explain this ah, ha, ha, ha",
			"Say my name and everything just stops<BREAKER>I don't want you like a best friend<BREAKER>Only bought this dress so you could take it off<BREAKER>Take it off<BREAKER>Carve your name into my bedpost<BREAKER>'Cause I don't want you like a best friend<BREAKER>Only bought this dress so you could take it off<BREAKER>Take it off",
			"There is an indentation in the shape of you<BREAKER>Only bought this dress so you could take it off<BREAKER>You made your mark on me, golden tattoo<BREAKER>Only bought this dress so you could take it off",
		],
	},
	{
		id: "rep-13",
		data_name: "this_is_why_we_cant_have_nice_things",
		title: "This Is Why We Can't Have Nice Things",
		lyrics: [
			"It was so nice throwing big parties<BREAKER>Jump into the pool from the balcony<BREAKER>Everyone swimming in a champagne sea<BREAKER>And there are no rules when you show up here<BREAKER>Bass beat rattling the chandelier<BREAKER>Feeling so Gatsby for that whole year",
			"So why'd you have to rain on my parade?<BREAKER>I'm shaking my head, I'm locking the gates",
			"This is why we can't have nice things, darling<BREAKER>Because you break them, I had to take them away<BREAKER>This is why we can't have nice things, honey (oh)<BREAKER>Did you think I wouldn't hear all the things you said about me?<BREAKER>This is why we can't have nice things",
			"It was so nice being friends again<BREAKER>There I was giving you a second chance<BREAKER>But you stabbed me in the back while shaking my hand<BREAKER>And therein lies the issue, friends don't try to trick you<BREAKER>Get you on the phone and mind-twist you<BREAKER>And so I took an axe to a mended fence",
			"But I'm not the only friend you've lost lately (mmm-mmm)<BREAKER>If only you weren't so shady",
			"This is why we can't have nice things, darling<BREAKER>Because you break them, I had to take them away<BREAKER>This is why we can't have nice (nice things) things (baby), honey (oh)<BREAKER>Did you think I wouldn't hear all the things you said about me?<BREAKER>This is why we can't have-",
			"Here's a toast to my real friends<BREAKER>They don't care about the he said, she said<BREAKER>And here's to my baby<BREAKER>He ain't reading what they call me lately<BREAKER>And here's to my mama<BREAKER>Had to listen to all this drama<BREAKER>And here's to you<BREAKER>'Cause forgiveness is a nice thing to do<BREAKER>Hahaha, I can't even say it with a straight face!",
			"This is why we can't have nice things, darling (darling)<BREAKER>Because you break them, I had to take them away<BREAKER>This is why we can't have nice (uh-uh) things (oh no), honey (baby, oh)<BREAKER>Did you think I wouldn't hear all the things you said about me?<BREAKER>This is why we can't have nice things, darling (oh)",
			"And here's to my real friends<BREAKER>(Oh) because you break them, I had to take them<BREAKER>And here's to my baby<BREAKER>(Oh) nice things, honey<BREAKER>They didn't care about the he said, she said<BREAKER>Did you think I wouldn't hear all the things you said about me?<BREAKER>This is why we can't have nice things",
		],
	},
	{
		id: "rep-14",
		data_name: "call_it_what_you_want",
		title: "Call It What You Want",
		lyrics: [
			"My castle crumbled overnight<BREAKER>I brought a knife to a gunfight<BREAKER>They took the crown, but it's alright<BREAKER>All the liars are calling me one<BREAKER>Nobody's heard from me for months<BREAKER>I'm doing better than I ever was",
			"'Cause my baby's fit like a daydream<BREAKER>Walkin' with his head down, I'm the one he's walkin' to<BREAKER>So call it what you want, yeah, call it what you want to<BREAKER>My baby's fly like a jet stream<BREAKER>High above the whole scene, loves me like I'm brand new<BREAKER>So call it what you want, yeah, call it what you want to",
			"All my flowers grew back as thorns<BREAKER>Windows boarded up after the storm<BREAKER>He built a fire just to keep me warm<BREAKER>All the drama queens taking swings<BREAKER>All the jokers dressin' up as kings<BREAKER>They fade to nothin' when I look at him",
			"And I know I make the same mistakes every time<BREAKER>Bridges burn, I never learn, at least I did one thing right<BREAKER>I did one thing right<BREAKER>I'm laughin' with my lover, makin' forts under covers<BREAKER>Trust him like a brother, yeah, you know I did one thing right<BREAKER>Starry eyes sparkin' up my darkest night",
			"My baby's fit like a daydream<BREAKER>Walkin' with his head down, I'm the one he's walkin' to<BREAKER>So call it what you want, yeah, call it what you want to<BREAKER>My baby's fly like a jet stream<BREAKER>High above the whole scene, loves me like I'm brand new<BREAKER>(Call it what you want, call it what you want, call it)<BREAKER>So call it what you want, yeah, call it what you want to",
			"I want to wear his initial<BREAKER>On a chain 'round my neck, chain 'round my neck<BREAKER>Not because he owns me<BREAKER>But 'cause he really knows me<BREAKER>Which is more than they can say, I<BREAKER>I recall late November<BREAKER>Holdin' my breath, slowly I said<BREAKER>\"You don't need to save me<BREAKER>But would you run away with me?\"<BREAKER>Yes (would you run away?)",
			"My baby's fit like a daydream<BREAKER>Walkin' with his head down, I'm the one he's walkin' to<BREAKER>(Call it what you want, call it what you want, call it)<BREAKER>So call it what you want, yeah, call it what you want to<BREAKER>My baby's fly like a jet stream<BREAKER>High above the whole scene, loves me like I'm brand new<BREAKER>(Call it what you want, call it what you want, call it)<BREAKER>So call it what you want, yeah, call it what you want to",
			"Call it what you want, yeah, call it what you want<BREAKER>To",
		],
	},
	{
		id: "rep-15",
		data_name: "new_years_day",
		title: "New Year's Day",
		lyrics: [
			"There's glitter on the floor after the party<BREAKER>Girls carrying their shoes down in the lobby<BREAKER>Candle wax and Polaroids on the hardwood floor<BREAKER>You and me from the night before, but",
			"Don't read the last page<BREAKER>But I stay when you're lost, and I'm scared, and you're turning away<BREAKER>I want your midnights<BREAKER>But I'll be cleaning up bottles with you on New Year's Day",
			"You squeeze my hand three times in the back of the taxi<BREAKER>I can tell that it's gonna be a long road<BREAKER>I'll be there if you're the toast of the town, babe<BREAKER>Or if you strike out and you're crawling home",
			"Don't read the last page<BREAKER>But I stay when it's hard, or it's wrong, or we're making mistakes<BREAKER>I want your midnights<BREAKER>But I'll be cleaning up bottles with you on New Year's Day",
			"Hold on to the memories<BREAKER>They will hold on to you<BREAKER>Hold on to the memories<BREAKER>They will hold on to you<BREAKER>Hold on to the memories<BREAKER>They will hold on to you<BREAKER>And I will hold on to you",
			"Please don't ever become a stranger<BREAKER>Whose laugh I could recognize anywhere<BREAKER>Please don't ever become a stranger<BREAKER>Whose laugh I could recognize anywhere",
			"There's glitter on the floor after the party<BREAKER>Girls carrying their shoes down in the lobby<BREAKER>Candle wax and Polaroids on the hardwood floor<BREAKER>You and me, forevermore",
			"Don't read the last page<BREAKER>But I stay when it's hard, or it's wrong, or we're making mistakes<BREAKER>I want your midnights<BREAKER>But I'll be cleaning up bottles with you on New Year's Day",
			"Hold on to the memories<BREAKER>They will hold on to you<BREAKER>Hold on to the memories<BREAKER>They will hold on to you<BREAKER>Hold on to the memories<BREAKER>They will hold on to you<BREAKER>And I will hold on to you",
			"Please don't ever become a stranger (hold on to the memories, they will hold on to you)<BREAKER>Whose laugh I could recognize anywhere (hold on to the memories, they will hold on to you)<BREAKER>Please don't ever become a stranger (hold on to the memories, they will hold on to you)<BREAKER>Whose laugh I could recognize anywhere (I will hold on to you)",
		],
	},
];

const selectSong = (song) => {
	const selectedSong = songsArr.filter((songObj) => songObj.data_name === song);
	return selectedSong;
};

export default selectSong;
